FROM node:22-alpine

WORKDIR /app

RUN npm config set registry https://registry.npmjs.org/
RUN npm config set fetch-retries 5

COPY package*.json ./

RUN npm install

COPY . .

CMD ["node", "worker.js"]